[package]
name = "manifest_schema"
edition.workspace = true

[dependencies]
# workspaces
gauntlet-server.workspace = true
schemars = "0.8"
serde_json = "1.0"

[features]
release = ["gauntlet-server/release"]
