[gauntlet]
name = 'Gauntlet'
description = 'Default Gauntlet functionality as a bundled plugin'

[[entrypoint]]
id = 'applications'
name = 'Applications'
path = 'src/applications.ts'
type = 'entrypoint-generator'
description = 'Run installed applications from your system'

[[entrypoint]]
id = 'settings'
name = 'Gauntlet Settings'
path = 'src/settings.tsx'
type = 'command'
description = 'Open Gauntlet Settings'

[[entrypoint]]
id = 'calculator'
name = 'Calculator'
path = 'src/calculator.tsx'
type = 'inline-view'
description = 'Calculator right under search bar'

[permissions]
main_search_bar = ["read"]
clipboard = ["write"]

[permissions.filesystem]
read = [
    # technically only uses locations defined by XDG Desktop Entry Specification, but
    # the spec allows for customization via XDG_DATA_DIRS and XDG_DATA_HOME env vars so it can be any path
    "/"
]

[[supported_system]]
os = 'linux'

[[supported_system]]
os = 'macos'

[[supported_system]]
os = 'windows'
